language: go
env:
  - GO111MODULE=on
go:
  - "1.12.x"
before_script:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -x -- -b $(go env GOPATH)/bin v1.17.1
script:
  - golangci-lint run
  - go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
  - "{ go tool cover -func=coverage.out | grep '^total:.*100.0%'; } || { echo 'FAIL - Coverage below 100%'; exit 1; }"
after_success:
  - bash <(curl -s https://codecov.io/bash)
